"""add prioridade to tarefa

Revision ID: 0e12730e1993
Revises: b8364cc94341
Create Date: 2026-09-29 19:51:25.774793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e12730e1993'
down_revision: Union[str, Sequence[str], None] = 'b8364cc94341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('prioridade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefa', 'prioridade')
    # ### end Alembic commands ###