"""add_ondelete_set_null_tarefa

Revision ID: 7c15261ef02a
Revises: 29eb68aad3dc
Create Date: 2026-03-16 21:16:34.684589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c15261ef02a'
down_revision: Union[str, Sequence[str], None] = '29eb68aad3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tarefa_dependencia_id_fkey'), 'tarefa', type_='foreignkey')
    op.create_foreign_key(None, 'tarefa', 'tarefa', ['dependencia_id'], ['id_tarefa'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.create_foreign_key(op.f('tarefa_dependencia_id_fkey'), 'tarefa', 'tarefa', ['dependencia_id'], ['id_tarefa'])
    # ### end Alembic commands ###