"""add board repository

Revision ID: a6a91b755ce7
Revises: b67af7761999
Create Date: 2026-10-06 10:34:32.483644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a91b755ce7'
down_revision: Union[str, Sequence[str], None] = 'b67af7761999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_name', sa.String(), nullable=False),
    sa.Column('repository_full_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id_board'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['github_installation_id'], ['github_installation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'repository_id', name='uq_board_repository')
    )
    op.create_index(op.f('ix_board_repository_id'), 'board_repository', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_repository_id'), table_name='board_repository')
    op.drop_table('board_repository')
    # ### end Alembic commands ###