"""add github installation

Revision ID: b67af7761999
Revises: 0e12730e1993
Create Date: 2026-09-29 22:12:44.524159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67af7761999'
down_revision: Union[str, Sequence[str], None] = '0e12730e1993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('repository_selection', sa.String(), nullable=True),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_email'], ['usuario.email'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installation_account_id'), 'github_installation', ['account_id'], unique=False)
    op.create_index(op.f('ix_github_installation_id'), 'github_installation', ['id'], unique=False)
    op.create_index(op.f('ix_github_installation_installation_id'), 'github_installation', ['installation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_installation_installation_id'), table_name='github_installation')
    op.drop_index(op.f('ix_github_installation_id'), table_name='github_installation')
    op.drop_index(op.f('ix_github_installation_account_id'), table_name='github_installation')
    op.drop_table('github_installation')
    # ### end Alembic commands ###