"""add board_membro table

Revision ID: b8364cc94341
Revises: 7c15261ef02a
Create Date: 2026-04-05 18:44:53.308651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8364cc94341'
down_revision: Union[str, Sequence[str], None] = '7c15261ef02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('usuario_email', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id_board'], ),
    sa.ForeignKeyConstraint(['usuario_email'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_membro_id'), 'board_membro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_membro_id'), table_name='board_membro')
    op.drop_table('board_membro')
    # ### end Alembic commands ###