"""inicial_railway_limpo

Revision ID: 29eb68aad3dc
Revises: 
Create Date: 2026-03-16 00:14:27.667426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eb68aad3dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_table('board',
    sa.Column('id_board', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('usuario_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_email'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('id_board')
    )
    op.create_index(op.f('ix_board_id_board'), 'board', ['id_board'], unique=False)
    op.create_table('chatia',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=True),
    sa.Column('resposta', sa.String(), nullable=True),
    sa.Column('usuario_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_email'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_index(op.f('ix_chatia_id_chat'), 'chatia', ['id_chat'], unique=False)
    op.create_table('tarefa',
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.Column('id_board', sa.Integer(), nullable=False),
    sa.Column('responsavel_email', sa.String(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependencia_id'], ['tarefa.id_tarefa'], ),
    sa.ForeignKeyConstraint(['id_board'], ['board.id_board'], ),
    sa.ForeignKeyConstraint(['responsavel_email'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('id_tarefa')
    )
    op.create_index(op.f('ix_tarefa_id_tarefa'), 'tarefa', ['id_tarefa'], unique=False)
    op.create_index(op.f('ix_tarefa_status'), 'tarefa', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefa_status'), table_name='tarefa')
    op.drop_index(op.f('ix_tarefa_id_tarefa'), table_name='tarefa')
    op.drop_table('tarefa')
    op.drop_index(op.f('ix_chatia_id_chat'), table_name='chatia')
    op.drop_table('chatia')
    op.drop_index(op.f('ix_board_id_board'), table_name='board')
    op.drop_table('board')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
